# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("timescaledb"),
        migrations.CreateModel(
            name="ReportedContentStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", timescale.db.models.fields.TimescaleDateTimeField(interval="1 day")),
                ("count", models.PositiveIntegerField()),
                ("subject_id", models.PositiveIntegerField()),
                ("market", models.CharField(choices=[("US", "us"), ("RU", "ru")], max_length=5)),
            ],
            options={
                "db_table": "reported_content_stats",
            },
        ),
    ]
