# Generated by Django 4.2.2 on 2023-07-07 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("market", models.CharField(choices=[("US", "us"), ("RU", "ru")], max_length=5)),
                ("logo", models.CharField(blank=True, default="", max_length=255, validators=[django.core.validators.URLValidator(["https"])])),
                ("leader", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="led_teams", to="moderators.moderator")),
                ("members", models.ManyToManyField(related_name="teams", to="moderators.moderator")),
            ],
            options={
                "db_table": "teams",
            },
        ),
    ]
