# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeLoginCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("source", models.CharField(max_length=30)),
                ("moderator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="one_time_login_codes", to="moderators.moderator")),
            ],
            options={
                "db_table": "one_time_login_codes",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("requires_registration", models.BooleanField()),
                ("notify_about_joins", models.BooleanField()),
                ("invitee", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="related_invites", to="moderators.moderator")),
                ("inviter", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="generated_invites", to="moderators.moderator")),
            ],
            options={
                "db_table": "invites",
            },
        ),
    ]
