# Generated by Django 4.2.2 on 2023-07-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("attachment_url", models.CharField(max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("from_moderator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sent_thanks", to="moderators.moderator")),
                ("to_moderator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="received_thanks", to="moderators.moderator")),
            ],
            options={
                "db_table": "thanks",
            },
        ),
    ]
